In [2]:
import numpy as np

# Numpy

In [2]:
vec = [1, 2, 3]

In [4]:
np_vec = np.array(vec)

In [5]:
np_vec

array([1, 2, 3])

In [6]:
type(np_vec)

numpy.ndarray

In [7]:
mat = [[2, 6, 9],[4, 8, 3]]

In [8]:
np_mat = np.array(mat)

In [9]:
np_mat

array([[2, 6, 9],
       [4, 8, 3]])

# Zeros, Ones, Eye

In [11]:
zero_mat = np.zeros((3, 4))

In [12]:
zero_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
one_mat = np.ones((3, 4))

In [14]:
one_mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
eye_mat = np.eye(4)

In [16]:
eye_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

In [17]:
np.random.randn(5)

array([-0.15131694,  0.50329313,  0.53011397,  0.41058424, -0.2429882 ])

In [18]:
np.random.randn(3,4)

array([[-0.91479255, -0.47823031,  2.27637856, -0.23137812],
       [-1.84594711, -0.58986964, -0.14432218,  0.43220616],
       [ 0.37388705, -1.28052911,  0.60168797, -1.15843614]])

# Array

In [12]:
a = np.array([0, 1, 2, 3])

In [4]:
a + 6 # sum 6 to every element of the array

array([6, 7, 8, 9])

In [5]:
np.sin(a) # calculates sin for every element of the array

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [8]:
np.sum(a) # sum all values in a

6

In [13]:
m1 = np.array([[0, 1],[3, 4]])
m2 = np.array([[4, 5],[6, 7]])

In [15]:
m1 * m2 # this is a element by element multiplication

array([[ 0,  5],
       [18, 28]])

In [17]:
m1.dot(m2) # this is a matrix multiplication

array([[ 6,  7],
       [36, 43]])

In [19]:
m1 > 2

array([[False, False],
       [ True,  True]])

In [20]:
m2.mean()

5.5

# Indexing, Slicing, Broadcasting

In [24]:
d1 = np.arange(25)

In [25]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
d2 = np.arange(25).reshape(5, 5)

In [27]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
 d1[4: 10] # returns an array containing elements from index 4 to 9

array([4, 5, 6, 7, 8, 9])

In [31]:
d1[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [32]:
d1[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
d2[:, 0] # all elements from first column

array([ 0,  5, 10, 15, 20])

In [47]:
d2[0,:] # all elements from first row

array([0, 1, 2, 3, 4])

In [49]:
d2[0, 0] # first element from first row and first column

0

In [50]:
d2[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [52]:
d1[0:5] = 5

In [53]:
d1

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])